name:                FPvsOO
version:             0.1.0.0
github:              "thma/FPvsOO"
license:             Apache-2.0
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2020 Thomas Mahler"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thma/FPvsOO#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  FPvsOO:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FPvsOO

tests:
  FPvsOO-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FPvsOO
    - hspec
    - QuickCheck
